# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d801d36278580cf36da1f98fd13b2971c50af3fa47e09ccfd6baed79321cc4be34b5d2fd96f79acd2f4fe5497ca82590316804200c6fdc4691de583b42c2690

test:
  secret_key_base: 72f21460649b1363536ab5b0e9f142a129da6c0dd2535f528c40a3cf088367c55487bd78d274edd205a0350a2ca5efb3df1a61a71b349c3cecca9100e293ff97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
